[package]
name = "rust-haunted-house"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
rand = "0.8.5"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
tokio = "1.41.1"
